export const productImages = {
  coke: require("./coke.png"),
  nike_huarache: require("./nike-huarache.png"),
  perfume: require("./perfume.png"),
  crayon_box: require("./crayon-box.png"),
  solong_coffee: require("./solong-coffee.png"),
  vans: require("./vans.png"),
  food_bag: require("./food-bag.png"),
  ps5: require("./ps5.jpg"),
  iphone: require("./iphone12.jpg"),
  samsungs21: require("./samsungs21.jpg"),
  samsungtv: require("./samsungseriestv.jpg"),
  sony_headset: require("./sony-headset.jpg"),
  avatar: require("./avatar.png"),
};
